# Generated by Django 5.1.5 on 2025-02-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_created_by_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('news', 'News'), ('announcement', 'Announcement')], default='blog', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Untitled Post', max_length=255),
        ),
    ]
